Make manual testing safer & simpler
Leaving PAT empty caused:

github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}